# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0510971b0d2a890e0a5666175ddf9e202e028a8a1f90d915533ad528cc801f27de1258edbd49d73e3c8ae4470fa25b0fac5da1d0a7b6cda5aaac792dff0263fc

test:
  secret_key_base: 11bbc6c18aecfe5dd88293a61896753c63023a6421ecb3a50006e47ceb17e93ab97513aec69a1b005ac2198d8b74a53d6ef578cb888d5ff48d8aa820e86e0db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
